apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: y727llpzj-nodejs 
  janus-idp.io/tekton: y727llpzj-nodejs
  backstage.io/kubernetes-id: y727llpzj-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: y727llpzj-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  