apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: y727llpzj-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: y727llpzj-nodejs 
  name: y727llpzj-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: y727llpzj-nodejs 
